<?php
/**
 * Where a style variation lives, and which design systems the site may wear.
 *
 * The theme ships 154 variations under styles/. A site can also WEAR A LOOK MADE AT RUNTIME —
 * the customer's own brand, generated by the Tracy build from Brand/<host>/tokens.css (ADR 0023)
 * — and that file cannot live in the theme directory: a theme update replaces the directory
 * wholesale and the brand's look would die with it. It lives under wp-content/uploads/tracy/,
 * which survives updates and travels with backups. Two pure helpers, so the resolution can be
 * tested with real PHP and no WordPress.
 *
 * @package tracy
 */

defined( 'ABSPATH' ) || exit;

/**
 * Where the variations Tracy writes at runtime live: `<uploads>/tracy/`.
 *
 * @return string An absolute directory, no trailing slash.
 */
function tracy_uploads_dir(): string {
	$uploads = wp_upload_dir();
	return rtrim( (string) ( $uploads['basedir'] ?? '' ), '/' ) . '/tracy';
}

/**
 * The JSON file of one style variation: the theme's own first, then the one Tracy wrote under
 * uploads. Null when neither exists.
 *
 * @param string $id A variation slug, `^[a-z0-9-]+$` — the caller checked.
 * @return string|null
 */
function tracy_variation_file( string $id ): ?string {
	$shipped = get_theme_file_path( "styles/$id.json" );
	if ( is_file( $shipped ) ) {
		return $shipped;
	}
	$written = tracy_uploads_dir() . "/styles/$id.json";
	return is_file( $written ) ? $written : null;
}

/**
 * The catalogue of design systems this site may wear: what the theme ships, plus every system
 * `<uploads>/tracy/inspirations.json` adds (a brand's variation registers itself there). A written
 * row wins over a shipped one of the same id, and a row of the wrong shape is ignored.
 *
 * @param array<string, array{name: string, category: string, nav: string, hero: string, dark: bool}> $shipped
 * @return array<string, array{name: string, category: string, nav: string, hero: string, dark: bool}>
 */
function tracy_inspirations_merged( array $shipped ): array {
	$file = tracy_uploads_dir() . '/inspirations.json';
	if ( ! is_file( $file ) ) {
		return $shipped;
	}
	$decoded = wp_json_file_decode( $file, array( 'associative' => true ) );
	$written = is_array( $decoded ) && isset( $decoded['systems'] ) && is_array( $decoded['systems'] ) ? $decoded['systems'] : array();
	foreach ( $written as $id => $row ) {
		if ( is_string( $id ) && preg_match( '/^[a-z0-9-]+$/', $id ) && is_array( $row ) && isset( $row['name'] ) && is_string( $row['name'] ) ) {
			$shipped[ $id ] = $row;
		}
	}
	return $shipped;
}
