<?php
/**
 * Title: Problem
 * Slug: tracy/section-problem
 * Categories: tracy
 * Description: Problem section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-problem py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-problem py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-section__inner max-w-page mx-auto"} -->
<div class="wp-block-group tracy-section__inner max-w-page mx-auto">
<!-- wp:group {"className":"tracy-section__head max-w-[62ch] mb-8"} -->
<div class="wp-block-group tracy-section__head max-w-[62ch] mb-8">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">The problem</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":2,"className":"text-2xl mb-3"} -->
<h2 class="wp-block-heading text-2xl mb-3">You're not slow. Your setup is.</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead mb-0"} -->
<p class="tracy-lead mb-0">Every site has its own login, its own plugin drift, its own way of breaking on a Friday.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-grid tracy-cards grid gap-6 sm:grid-cols-2 lg:grid-cols-3"} -->
<div class="wp-block-group tracy-grid tracy-cards grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
<!-- wp:group {"className":"tracy-card p-6"} -->
<div class="wp-block-group tracy-card p-6">
<!-- wp:heading {"level":3,"className":"text-lg mb-2"} -->
<h3 class="wp-block-heading text-lg mb-2">Ten dashboards</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"mb-0"} -->
<p class="mb-0">Each site wants you inside its own admin before anything can change.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card p-6"} -->
<div class="wp-block-group tracy-card p-6">
<!-- wp:heading {"level":3,"className":"text-lg mb-2"} -->
<h3 class="wp-block-heading text-lg mb-2">Changes nobody reviewed</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"mb-0"} -->
<p class="mb-0">An edit made in a hurry is live the moment it is saved, and gone from memory the next day.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card p-6"} -->
<div class="wp-block-group tracy-card p-6">
<!-- wp:heading {"level":3,"className":"text-lg mb-2"} -->
<h3 class="wp-block-heading text-lg mb-2">No way back</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"mb-0"} -->
<p class="mb-0">When something breaks, the only undo is a backup from last week.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
