<?php
/**
 * Title: Gallery
 * Slug: tracy/section-gallery
 * Categories: tracy
 * Description: Gallery section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-gallery py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-gallery py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-section__inner max-w-page mx-auto"} -->
<div class="wp-block-group tracy-section__inner max-w-page mx-auto">
<!-- wp:group {"className":"tracy-section__head max-w-[62ch] mb-8"} -->
<div class="wp-block-group tracy-section__head max-w-[62ch] mb-8">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Gallery</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":2,"className":"text-2xl mb-3"} -->
<h2 class="wp-block-heading text-2xl mb-3">Work, as it was actually shipped</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead mb-0"} -->
<p class="tracy-lead mb-0">No mockups on a desk. Screens from sites that are live right now.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-grid tracy-gallery__grid grid gap-4 sm:grid-cols-2 lg:grid-cols-3"} -->
<div class="wp-block-group tracy-grid tracy-gallery__grid grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
<!-- wp:group {"className":"tracy-card tracy-shot"} -->
<div class="wp-block-group tracy-card tracy-shot">
<!-- wp:image {"className":"tracy-card__media tracy-shot__media m-0"} -->
<figure class="wp-block-image tracy-card__media tracy-shot__media m-0"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
<!-- wp:paragraph {"className":"tracy-shot__caption tracy-meta p-3 mb-0"} -->
<p class="tracy-shot__caption tracy-meta p-3 mb-0">Ban Giay — coffee house, Da Nang</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card tracy-shot"} -->
<div class="wp-block-group tracy-card tracy-shot">
<!-- wp:image {"className":"tracy-card__media tracy-shot__media m-0"} -->
<figure class="wp-block-image tracy-card__media tracy-shot__media m-0"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
<!-- wp:paragraph {"className":"tracy-shot__caption tracy-meta p-3 mb-0"} -->
<p class="tracy-shot__caption tracy-meta p-3 mb-0">Halden Studio — architecture, Oslo</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card tracy-shot"} -->
<div class="wp-block-group tracy-card tracy-shot">
<!-- wp:image {"className":"tracy-card__media tracy-shot__media m-0"} -->
<figure class="wp-block-image tracy-card__media tracy-shot__media m-0"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
<!-- wp:paragraph {"className":"tracy-shot__caption tracy-meta p-3 mb-0"} -->
<p class="tracy-shot__caption tracy-meta p-3 mb-0">Meridian Legal — law, Singapore</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card tracy-shot"} -->
<div class="wp-block-group tracy-card tracy-shot">
<!-- wp:image {"className":"tracy-card__media tracy-shot__media m-0"} -->
<figure class="wp-block-image tracy-card__media tracy-shot__media m-0"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
<!-- wp:paragraph {"className":"tracy-shot__caption tracy-meta p-3 mb-0"} -->
<p class="tracy-shot__caption tracy-meta p-3 mb-0">Red Dragon — restaurant, Hanoi</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card tracy-shot"} -->
<div class="wp-block-group tracy-card tracy-shot">
<!-- wp:image {"className":"tracy-card__media tracy-shot__media m-0"} -->
<figure class="wp-block-image tracy-card__media tracy-shot__media m-0"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
<!-- wp:paragraph {"className":"tracy-shot__caption tracy-meta p-3 mb-0"} -->
<p class="tracy-shot__caption tracy-meta p-3 mb-0">Northline Freight — haulage, Leeds</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card tracy-shot"} -->
<div class="wp-block-group tracy-card tracy-shot">
<!-- wp:image {"className":"tracy-card__media tracy-shot__media m-0"} -->
<figure class="wp-block-image tracy-card__media tracy-shot__media m-0"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
<!-- wp:paragraph {"className":"tracy-shot__caption tracy-meta p-3 mb-0"} -->
<p class="tracy-shot__caption tracy-meta p-3 mb-0">Wingspan Club — sport, Hue</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
