<?php
/**
 * Title: Call to action, final
 * Slug: tracy/section-cta-final
 * Categories: tracy
 * Description: Call to action, final section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-cta-final py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-cta-final py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-cta-final__box max-w-page mx-auto bg-accent text-accent-on rounded-lg py-12 px-8 text-center"} -->
<div class="wp-block-group tracy-cta-final__box max-w-page mx-auto bg-accent text-accent-on rounded-lg py-12 px-8 text-center">
<!-- wp:heading {"level":2,"className":"text-2xl text-inherit mb-3"} -->
<h2 class="wp-block-heading text-2xl text-inherit mb-3">Start building with Tracy today</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead text-inherit opacity-90 mx-auto"} -->
<p class="tracy-lead text-inherit opacity-90 mx-auto">One desk for every site you run, with a change log you can trust.</p>
<!-- /wp:paragraph -->
<!-- wp:buttons {"className":"tracy-actions justify-center"} -->
<div class="wp-block-buttons tracy-actions justify-center">
<!-- wp:button {"className":"tracy-btn tracy-btn--inverse"} -->
<div class="wp-block-button tracy-btn tracy-btn--inverse"><a class="wp-block-button__link wp-element-button" href="#">Get started</a></div>
<!-- /wp:button -->
<!-- wp:button {"className":"is-style-outline tracy-btn tracy-btn--ghost"} -->
<div class="wp-block-button is-style-outline tracy-btn tracy-btn--ghost"><a class="wp-block-button__link wp-element-button" href="#">Talk to us</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons -->
<!-- wp:paragraph {"className":"tracy-meta tracy-cta-final__note text-inherit opacity-80 mt-4 mb-0"} -->
<p class="tracy-meta tracy-cta-final__note text-inherit opacity-80 mt-4 mb-0">2-minute setup · Cancel anytime</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
