<?php
/**
 * Title: Style guide
 * Slug: tracy/section-styleguide
 * Categories: tracy
 * Description: Style guide section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-guide py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-guide py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-section__inner max-w-page mx-auto"} -->
<div class="wp-block-group tracy-section__inner max-w-page mx-auto">
<!-- wp:group {"className":"tracy-section__head max-w-[62ch] mb-8"} -->
<div class="wp-block-group tracy-section__head max-w-[62ch] mb-8">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Style guide</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":2,"className":"text-2xl mb-3"} -->
<h2 class="wp-block-heading text-2xl mb-3">How this site speaks</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead mb-0"} -->
<p class="tracy-lead mb-0">Type, colour, spacing and corners, drawn from the tokens the whole site is built on.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:heading {"level":3,"className":"text-lg mt-8 mb-4"} -->
<h3 class="wp-block-heading text-lg mt-8 mb-4">Type scale</h3>
<!-- /wp:heading -->
<!-- wp:group {"className":"tracy-guide__scale grid gap-4 mb-8"} -->
<div class="wp-block-group tracy-guide__scale grid gap-4 mb-8">
<!-- wp:heading {"level":1,"className":"tracy-display m-0"} -->
<h1 class="wp-block-heading tracy-display m-0">Every page starts with one clear sentence.</h1>
<!-- /wp:heading -->
<!-- wp:heading {"level":2,"className":"text-2xl m-0"} -->
<h2 class="wp-block-heading text-2xl m-0">Sections read as a sequence of assertions.</h2>
<!-- /wp:heading -->
<!-- wp:heading {"level":3,"className":"text-lg m-0"} -->
<h3 class="wp-block-heading text-lg m-0">Cards, tabs and dialogs share this size.</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead m-0"} -->
<p class="tracy-lead m-0">The lead paragraph sets the pace: one idea, said once.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"m-0"} -->
<p class="m-0">Body text carries the argument. It should read at arm's length on a phone and stay calm on a wide screen, with a measure of about seventy characters.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-meta m-0"} -->
<p class="tracy-meta m-0">Small text is for metadata, timestamps and helper lines, never for anything the reader must not miss.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-eyebrow m-0"} -->
<p class="tracy-eyebrow m-0">Eyebrow · uppercase mono</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:heading {"level":3,"className":"text-lg mt-8 mb-4"} -->
<h3 class="wp-block-heading text-lg mt-8 mb-4">Colour roles</h3>
<!-- /wp:heading -->
<!-- wp:group {"className":"tracy-guide__swatches flex flex-wrap gap-4 mb-8"} -->
<div class="wp-block-group tracy-guide__swatches flex flex-wrap gap-4 mb-8">
<!-- wp:paragraph {"className":"tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-bg text-fg"} -->
<p class="tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-bg text-fg">Background</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-surface text-fg"} -->
<p class="tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-surface text-fg">Surface</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-surface-warm text-fg"} -->
<p class="tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-surface-warm text-fg">Surface warm</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-fg text-bg"} -->
<p class="tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-fg text-bg">Foreground</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-muted text-bg"} -->
<p class="tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-muted text-bg">Muted</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-accent text-accent-on"} -->
<p class="tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-accent text-accent-on">Accent</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-success text-bg"} -->
<p class="tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-success text-bg">Success</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-warn text-fg"} -->
<p class="tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-warn text-fg">Warn</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-danger text-bg"} -->
<p class="tracy-swatch w-[9rem] h-[6rem] m-0 p-3 flex items-end rounded-md border border-border-soft font-mono text-xs bg-danger text-bg">Danger</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:heading {"level":3,"className":"text-lg mt-8 mb-4"} -->
<h3 class="wp-block-heading text-lg mt-8 mb-4">Buttons</h3>
<!-- /wp:heading -->
<!-- wp:buttons {"className":"tracy-actions mb-8"} -->
<div class="wp-block-buttons tracy-actions mb-8">
<!-- wp:button {"className":"tracy-btn tracy-btn--primary"} -->
<div class="wp-block-button tracy-btn tracy-btn--primary"><a class="wp-block-button__link wp-element-button" href="#">Primary action</a></div>
<!-- /wp:button -->
<!-- wp:button {"className":"is-style-outline tracy-btn tracy-btn--ghost"} -->
<div class="wp-block-button is-style-outline tracy-btn tracy-btn--ghost"><a class="wp-block-button__link wp-element-button" href="#">Secondary action</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons -->
<!-- wp:heading {"level":3,"className":"text-lg mt-8 mb-4"} -->
<h3 class="wp-block-heading text-lg mt-8 mb-4">Spacing and corners</h3>
<!-- /wp:heading -->
<!-- wp:group {"className":"tracy-guide__ladder flex flex-wrap items-end gap-4 mb-8"} -->
<div class="wp-block-group tracy-guide__ladder flex flex-wrap items-end gap-4 mb-8">
<!-- wp:paragraph {"className":"tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-1)*4)] h-[calc(var(--space-1)*4)]"} -->
<p class="tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-1)*4)] h-[calc(var(--space-1)*4)]">1</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-2)*4)] h-[calc(var(--space-2)*4)]"} -->
<p class="tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-2)*4)] h-[calc(var(--space-2)*4)]">2</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-4)*4)] h-[calc(var(--space-4)*4)]"} -->
<p class="tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-4)*4)] h-[calc(var(--space-4)*4)]">4</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-6)*4)] h-[calc(var(--space-6)*4)]"} -->
<p class="tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-6)*4)] h-[calc(var(--space-6)*4)]">6</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-8)*4)] h-[calc(var(--space-8)*4)]"} -->
<p class="tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-8)*4)] h-[calc(var(--space-8)*4)]">8</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-12)*4)] h-[calc(var(--space-12)*4)]"} -->
<p class="tracy-step-box m-0 grid place-items-center bg-accent text-accent-on font-mono text-xs rounded-sm w-[calc(var(--space-12)*4)] h-[calc(var(--space-12)*4)]">12</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-guide__radii flex flex-wrap items-end gap-4"} -->
<div class="wp-block-group tracy-guide__radii flex flex-wrap items-end gap-4">
<!-- wp:paragraph {"className":"tracy-radius-box m-0 w-[8rem] h-[5rem] grid place-items-center bg-surface border border-border font-mono text-xs rounded-sm"} -->
<p class="tracy-radius-box m-0 w-[8rem] h-[5rem] grid place-items-center bg-surface border border-border font-mono text-xs rounded-sm">radius sm</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-radius-box m-0 w-[8rem] h-[5rem] grid place-items-center bg-surface border border-border font-mono text-xs rounded-md"} -->
<p class="tracy-radius-box m-0 w-[8rem] h-[5rem] grid place-items-center bg-surface border border-border font-mono text-xs rounded-md">radius md</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-radius-box m-0 w-[8rem] h-[5rem] grid place-items-center bg-surface border border-border font-mono text-xs rounded-lg"} -->
<p class="tracy-radius-box m-0 w-[8rem] h-[5rem] grid place-items-center bg-surface border border-border font-mono text-xs rounded-lg">radius lg</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-radius-box m-0 w-[8rem] h-[5rem] grid place-items-center bg-surface border border-border font-mono text-xs rounded-pill"} -->
<p class="tracy-radius-box m-0 w-[8rem] h-[5rem] grid place-items-center bg-surface border border-border font-mono text-xs rounded-pill">pill</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
