<?php
/**
 * Title: Proof
 * Slug: tracy/section-proof
 * Categories: tracy
 * Description: Proof section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-stats bg-accent text-accent-on py-12 px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-stats bg-accent text-accent-on py-12 px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-grid tracy-stats__grid max-w-page mx-auto grid gap-6 grid-cols-2 lg:grid-cols-4 text-center"} -->
<div class="wp-block-group tracy-grid tracy-stats__grid max-w-page mx-auto grid gap-6 grid-cols-2 lg:grid-cols-4 text-center">
<!-- wp:group {"className":"tracy-stat"} -->
<div class="wp-block-group tracy-stat">
<!-- wp:paragraph {"className":"tracy-stat__n font-display text-2xl leading-tight tracking-display whitespace-nowrap mb-1"} -->
<p class="tracy-stat__n font-display text-2xl leading-tight tracking-display whitespace-nowrap mb-1">12,000+</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-stat__label text-sm opacity-85 mb-0"} -->
<p class="tracy-stat__label text-sm opacity-85 mb-0">Teams on board</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-stat"} -->
<div class="wp-block-group tracy-stat">
<!-- wp:paragraph {"className":"tracy-stat__n font-display text-2xl leading-tight tracking-display whitespace-nowrap mb-1"} -->
<p class="tracy-stat__n font-display text-2xl leading-tight tracking-display whitespace-nowrap mb-1">4.9/5</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-stat__label text-sm opacity-85 mb-0"} -->
<p class="tracy-stat__label text-sm opacity-85 mb-0">Average rating</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-stat"} -->
<div class="wp-block-group tracy-stat">
<!-- wp:paragraph {"className":"tracy-stat__n font-display text-2xl leading-tight tracking-display whitespace-nowrap mb-1"} -->
<p class="tracy-stat__n font-display text-2xl leading-tight tracking-display whitespace-nowrap mb-1">3.2s</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-stat__label text-sm opacity-85 mb-0"} -->
<p class="tracy-stat__label text-sm opacity-85 mb-0">Median response</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-stat"} -->
<div class="wp-block-group tracy-stat">
<!-- wp:paragraph {"className":"tracy-stat__n font-display text-2xl leading-tight tracking-display whitespace-nowrap mb-1"} -->
<p class="tracy-stat__n font-display text-2xl leading-tight tracking-display whitespace-nowrap mb-1">100%</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-stat__label text-sm opacity-85 mb-0"} -->
<p class="tracy-stat__label text-sm opacity-85 mb-0">Changes reversible</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-testimonials py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-testimonials py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-section__inner max-w-page mx-auto"} -->
<div class="wp-block-group tracy-section__inner max-w-page mx-auto">
<!-- wp:group {"className":"tracy-section__head max-w-[62ch] mb-8"} -->
<div class="wp-block-group tracy-section__head max-w-[62ch] mb-8">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Proof</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":2,"className":"text-2xl mb-3"} -->
<h2 class="wp-block-heading text-2xl mb-3">Loved by the teams who use it daily</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead mb-0"} -->
<p class="tracy-lead mb-0">Real results, in their words, not ours.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-grid tracy-cards grid gap-6 sm:grid-cols-2 lg:grid-cols-3"} -->
<div class="wp-block-group tracy-grid tracy-cards grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
<!-- wp:group {"className":"tracy-card p-6"} -->
<div class="wp-block-group tracy-card p-6">
<!-- wp:quote {"className":"tracy-quote"} -->
<blockquote class="wp-block-quote tracy-quote"><!-- wp:paragraph {"className":"text-lg text-fg"} -->
<p class="text-lg text-fg">"We stopped dreading the Friday deploy. The review step alone paid for itself."</p>
<!-- /wp:paragraph --><cite>Mai, agency lead</cite></blockquote>
<!-- /wp:quote -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card p-6"} -->
<div class="wp-block-group tracy-card p-6">
<!-- wp:quote {"className":"tracy-quote"} -->
<blockquote class="wp-block-quote tracy-quote"><!-- wp:paragraph {"className":"text-lg text-fg"} -->
<p class="text-lg text-fg">"Eleven client sites, one desk. I had not opened a WordPress admin in a month."</p>
<!-- /wp:paragraph --><cite>Daniel, freelancer</cite></blockquote>
<!-- /wp:quote -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card p-6"} -->
<div class="wp-block-group tracy-card p-6">
<!-- wp:quote {"className":"tracy-quote"} -->
<blockquote class="wp-block-quote tracy-quote"><!-- wp:paragraph {"className":"text-lg text-fg"} -->
<p class="text-lg text-fg">"The first time a change went wrong, we put it back in one call. That was the moment."</p>
<!-- /wp:paragraph --><cite>Priya, head of web</cite></blockquote>
<!-- /wp:quote -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
