<?php
/**
 * Title: Pricing plans
 * Slug: tracy/section-pricing
 * Categories: tracy
 * Description: Pricing plans section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-plans py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-plans py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-section__inner max-w-page mx-auto"} -->
<div class="wp-block-group tracy-section__inner max-w-page mx-auto">
<!-- wp:group {"className":"tracy-section__head max-w-[62ch] mb-8"} -->
<div class="wp-block-group tracy-section__head max-w-[62ch] mb-8">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Pricing</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":2,"className":"text-2xl mb-3"} -->
<h2 class="wp-block-heading text-2xl mb-3">Plans that scale with you</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead mb-0"} -->
<p class="tracy-lead mb-0">Start free. Upgrade only when it earns it.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-grid tracy-plans__grid grid gap-6 sm:grid-cols-2 lg:grid-cols-3"} -->
<div class="wp-block-group tracy-grid tracy-plans__grid grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
<!-- wp:group {"className":"tracy-card tracy-plan p-6 flex flex-col"} -->
<div class="wp-block-group tracy-card tracy-plan p-6 flex flex-col">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Starter</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"tracy-plan__price text-3xl m-0"} -->
<h3 class="wp-block-heading tracy-plan__price text-3xl m-0">$29</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-meta"} -->
<p class="tracy-meta">per month, one site</p>
<!-- /wp:paragraph -->
<!-- wp:list {"className":"tracy-plan__list flex-1 my-4 mb-6"} -->
<ul class="wp-block-list tracy-plan__list flex-1 my-4 mb-6">
<!-- wp:list-item {"className":"py-2 border-t border-border-soft"} -->
<li class="py-2 border-t border-border-soft">1 site, 1 agent</li>
<!-- /wp:list-item -->
<!-- wp:list-item {"className":"py-2 border-t border-border-soft"} -->
<li class="py-2 border-t border-border-soft">Review before publish</li>
<!-- /wp:list-item -->
<!-- wp:list-item {"className":"py-2 border-t border-border-soft"} -->
<li class="py-2 border-t border-border-soft">Email support</li>
<!-- /wp:list-item -->
</ul>
<!-- /wp:list -->
<!-- wp:buttons {"className":"tracy-actions"} -->
<div class="wp-block-buttons tracy-actions">
<!-- wp:button {"className":"is-style-outline tracy-btn tracy-btn--ghost"} -->
<div class="wp-block-button is-style-outline tracy-btn tracy-btn--ghost"><a class="wp-block-button__link wp-element-button" href="#">Choose Starter</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card tracy-plan is-hot p-6 flex flex-col border-accent shadow-[0_0_0_2px_var(--accent),var(--elev-raised)]"} -->
<div class="wp-block-group tracy-card tracy-plan is-hot p-6 flex flex-col border-accent shadow-[0_0_0_2px_var(--accent),var(--elev-raised)]">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Team · most popular</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"tracy-plan__price text-3xl m-0"} -->
<h3 class="wp-block-heading tracy-plan__price text-3xl m-0">$99</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-meta"} -->
<p class="tracy-meta">per month, ten sites</p>
<!-- /wp:paragraph -->
<!-- wp:list {"className":"tracy-plan__list flex-1 my-4 mb-6"} -->
<ul class="wp-block-list tracy-plan__list flex-1 my-4 mb-6">
<!-- wp:list-item {"className":"py-2 border-t border-border-soft"} -->
<li class="py-2 border-t border-border-soft">10 sites, 5 agents</li>
<!-- /wp:list-item -->
<!-- wp:list-item {"className":"py-2 border-t border-border-soft"} -->
<li class="py-2 border-t border-border-soft">Review before publish</li>
<!-- /wp:list-item -->
<!-- wp:list-item {"className":"py-2 border-t border-border-soft"} -->
<li class="py-2 border-t border-border-soft">Priority support</li>
<!-- /wp:list-item -->
</ul>
<!-- /wp:list -->
<!-- wp:buttons {"className":"tracy-actions"} -->
<div class="wp-block-buttons tracy-actions">
<!-- wp:button {"className":"tracy-btn tracy-btn--primary"} -->
<div class="wp-block-button tracy-btn tracy-btn--primary"><a class="wp-block-button__link wp-element-button" href="#">Choose Team</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card tracy-plan p-6 flex flex-col"} -->
<div class="wp-block-group tracy-card tracy-plan p-6 flex flex-col">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Agency</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"tracy-plan__price text-3xl m-0"} -->
<h3 class="wp-block-heading tracy-plan__price text-3xl m-0">$299</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-meta"} -->
<p class="tracy-meta">per month, unlimited</p>
<!-- /wp:paragraph -->
<!-- wp:list {"className":"tracy-plan__list flex-1 my-4 mb-6"} -->
<ul class="wp-block-list tracy-plan__list flex-1 my-4 mb-6">
<!-- wp:list-item {"className":"py-2 border-t border-border-soft"} -->
<li class="py-2 border-t border-border-soft">Unlimited sites and agents</li>
<!-- /wp:list-item -->
<!-- wp:list-item {"className":"py-2 border-t border-border-soft"} -->
<li class="py-2 border-t border-border-soft">Review before publish</li>
<!-- /wp:list-item -->
<!-- wp:list-item {"className":"py-2 border-t border-border-soft"} -->
<li class="py-2 border-t border-border-soft">Dedicated support</li>
<!-- /wp:list-item -->
</ul>
<!-- /wp:list -->
<!-- wp:buttons {"className":"tracy-actions"} -->
<div class="wp-block-buttons tracy-actions">
<!-- wp:button {"className":"is-style-outline tracy-btn tracy-btn--ghost"} -->
<div class="wp-block-button is-style-outline tracy-btn tracy-btn--ghost"><a class="wp-block-button__link wp-element-button" href="#">Talk to us</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
<!-- wp:paragraph {"className":"tracy-meta tracy-plans__note text-center mt-6 mb-0"} -->
<p class="tracy-meta tracy-plans__note text-center mt-6 mb-0">All prices in USD · Cancel anytime · No credit card to start.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
