<?php

/**
 * tpl_tracy — one template, 152 looks.
 *
 * The look is a template style parameter: `inspiration` names one of the OpenDesign design systems
 * bundled under media/css/inspirations/, and that file's :root is the only source of colour, type,
 * spacing, corners and shadows (tracy.css is written against those 56 names and declares none of
 * its own). `nav` and `hero` pick the layout; `auto` follows what inspirations.json says about the
 * chosen design system. Layout is CSS keyed on <body data-nav data-hero>, so switching the style
 * parameter changes the whole site without touching content.
 *
 * @package tpl_tracy
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Uri\Uri;

/** @var Joomla\CMS\Document\HtmlDocument $this */

$app   = Factory::getApplication();
$input = $app->getInput();
$wa    = $this->getWebAssetManager();

require_once __DIR__ . '/resolve.php';
$look = tpl_tracy_resolve($this->params);

// The motion effects this site has switched on, from the `motion` template style parameter: the
// stored `effects` list as written, each entry an id with the library version and intensity it was
// written for. A missing, empty or unparseable parameter means all off; an id the library does not
// know passes through untouched, because the runtime ignores what it cannot name.
$motionStored  = (string) $this->params->get('motion', '');
$motionDecoded = $motionStored === '' ? null : json_decode($motionStored, true);
$motion        = is_array($motionDecoded) && isset($motionDecoded['effects']) && is_array($motionDecoded['effects'])
    ? array_values($motionDecoded['effects'])
    : [];

// The component renders before index.php, so a Tracy layout has already told us which page kind
// this is. Anything else is derived from the request.
$page = (string) $app->get('tracy.page', '');
if ($page === '') {
    $view = $input->getCmd('view', '');
    $page = $view === 'category' ? 'listing' : ($view === 'article' ? 'article' : 'page');
}

// Joomla names a template's language file tpl_<element>.ini, and this template's element is
// tpl_tracy — so the file is tpl_tpl_tracy.ini. The admin style form derives that name itself;
// loading anything else here would translate the site and leave the admin form on raw keys.
$app->getLanguage()->load('tpl_tpl_tracy', JPATH_BASE);

// A root-relative path (no leading slash): the asset manager prefixes the site root itself.
if ($page === 'fixture' || $page === 'artifact') {
    // A design page (the system's own fixture, or an engine artifact): its fenced stylesheet is
    // registered by the layout; here only fixture-page.css, plus the motion sheet registered below
    // when an effect is on. Still nothing of the template's own: the motion entries declare no
    // dependency, so registering them drags none of it in behind them.
    $wa->registerAndUseStyle('template.fixture-page', 'media/templates/site/tpl_tracy/css/fixture-page.css');
} else {
    $wa->useStyle('template.tracy')
        ->useStyle('template.layout')
        ->useStyle('template.sections')
        ->useScript('template.tracy')
        ->registerAndUseStyle(
            'template.inspiration',
            'media/templates/site/tpl_tracy/css/inspirations/' . $look['id'] . '.css',
            [],
            [],
            ['template.tracy']
        );
}

// The live-preview agent, on EVERY page kind — the design pages included, since those are the ones
// someone watches while an inspiration is being tried on. No dependency, so activating it drags
// none of the template's own styles onto a page that carries none. It is inert outside a frame, so
// a visitor pays one deferred kilobyte; inside the side card's Browser tab it lets a stylesheet
// change repaint without reloading the page out from under whoever is reading it. The file is
// generated by packages/cms/tracy-cms-preview — read it there rather than editing it here.
$wa->useScript('template.preview');

// The motion library, on every page kind that has an effect switched on. Neither entry declares a
// dependency, so registering it on a design page drags none of the template's own styles in behind
// it. The config global goes before the library tag, re-encoded from the parsed parameter so
// nothing stored can break out of the script element, and it declares the dependency itself
// because that is what gives an inline asset's `before` position effect. The head marker below
// shares this condition; motion-head.php is generated by packages/cms/tracy-cms-motion, so read
// it there rather than editing it here.
if ($motion !== []) {
    $wa->useStyle('template.motion')
        ->useScript('template.motion')
        ->addInlineScript(
            'window.TracyMotion = ' . json_encode(
                ['effects' => $motion],
                JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT
            ) . ';',
            ['position' => 'before'],
            [],
            ['template.motion']
        );
}

// Last, once every sheet of this template is registered: each one's version follows its file, so a
// look change that rewrites it reaches every browser at once (resolve.php).
tpl_tracy_stamp_styles($wa, JPATH_ROOT);
$this->setMetaData('viewport', 'width=device-width, initial-scale=1');

$sitename = htmlspecialchars((string) $app->get('sitename'), ENT_QUOTES, 'UTF-8');
$hasNav   = $this->countModules('nav', true);
$hasSide  = $this->countModules('sidebar', true);
?>
<!DOCTYPE html>
<html lang="<?php echo $this->language; ?>" dir="<?php echo $this->direction; ?>">
<head>
    <?php if ($motion !== []) : ?>
        <?php require __DIR__ . '/motion-head.php'; ?>
    <?php endif; ?>
    <jdoc:include type="metas" />
    <jdoc:include type="styles" />
    <jdoc:include type="scripts" />
</head>
<body class="tracy tracy-page-<?php echo $page; ?>" data-inspiration="<?php echo $look['id']; ?>" data-nav="<?php echo $look['nav']; ?>" data-hero="<?php echo $look['hero']; ?>" data-page="<?php echo $page; ?>">
    <a class="tracy-skip" href="#tracy-main"><?php echo Text::_('TPL_TRACY_SKIP_TO_CONTENT'); ?></a>

    <header class="tracy-header">
        <div class="tracy-header__inner tracy-container">
            <a class="tracy-brand" href="<?php echo Uri::root(); ?>"><?php echo $sitename; ?></a>
            <?php if ($hasNav) : ?>
                <button class="tracy-nav-toggle" type="button" aria-expanded="false" aria-controls="tracy-nav">
                    <?php echo Text::_('TPL_TRACY_MENU'); ?>
                </button>
                <nav id="tracy-nav" class="tracy-nav" aria-label="<?php echo Text::_('TPL_TRACY_MENU'); ?>">
                    <jdoc:include type="modules" name="nav" style="none" />
                </nav>
            <?php endif; ?>
        </div>
    </header>

    <main id="tracy-main" class="tracy-main">
        <jdoc:include type="message" />
        <jdoc:include type="component" />
    </main>

    <?php if ($hasSide) : ?>
        <aside class="tracy-sidebar">
            <div class="tracy-container">
                <jdoc:include type="modules" name="sidebar" style="card" />
            </div>
        </aside>
    <?php endif; ?>

    <footer class="tracy-footer">
        <?php if ($this->countModules('footer', true)) : ?>
            <div class="tracy-footer__modules tracy-container">
                <jdoc:include type="modules" name="footer" style="card" />
            </div>
        <?php endif; ?>
        <div class="tracy-footer__inner tracy-container">
            <a class="tracy-footer__brand" href="<?php echo Uri::root(); ?>"><?php echo $sitename; ?></a>
            <p class="tracy-footer__note"><?php echo Text::_('TPL_TRACY_BUILT_WITH'); ?></p>
        </div>
    </footer>

    <jdoc:include type="modules" name="debug" style="none" />
</body>
</html>
