<?php
/**
 * Title: Value pillars
 * Slug: tracy/section-pillars
 * Categories: tracy
 * Description: Value pillars section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-section--band tracy-pillars bg-surface border-y border-border-soft py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-section--band tracy-pillars bg-surface border-y border-border-soft py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-section__inner max-w-page mx-auto"} -->
<div class="wp-block-group tracy-section__inner max-w-page mx-auto">
<!-- wp:group {"className":"tracy-section__head max-w-[62ch] mb-8"} -->
<div class="wp-block-group tracy-section__head max-w-[62ch] mb-8">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Why Tracy</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":2,"className":"text-2xl mb-3"} -->
<h2 class="wp-block-heading text-2xl mb-3">Here's how that changes</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead mb-0"} -->
<p class="tracy-lead mb-0">Three ways Tracy turns the daily grind into something you actually look forward to.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-grid tracy-pillars__grid grid gap-6 sm:grid-cols-2 lg:grid-cols-3"} -->
<div class="wp-block-group tracy-grid tracy-pillars__grid grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
<!-- wp:group {"className":"tracy-pillar pt-4 border-t-2 border-accent"} -->
<div class="wp-block-group tracy-pillar pt-4 border-t-2 border-accent">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">01</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"text-lg mb-2"} -->
<h3 class="wp-block-heading text-lg mb-2">One desk</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"mb-0"} -->
<p class="mb-0">Every site you run, in one place, with an agent that already knows its way around.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-pillar pt-4 border-t-2 border-accent"} -->
<div class="wp-block-group tracy-pillar pt-4 border-t-2 border-accent">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">02</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"text-lg mb-2"} -->
<h3 class="wp-block-heading text-lg mb-2">Review before live</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"mb-0"} -->
<p class="mb-0">Work is drafted and reviewed before anything reaches the running site.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-pillar pt-4 border-t-2 border-accent"} -->
<div class="wp-block-group tracy-pillar pt-4 border-t-2 border-accent">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">03</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"text-lg mb-2"} -->
<h3 class="wp-block-heading text-lg mb-2">Every change can be taken back</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"mb-0"} -->
<p class="mb-0">One call puts a whole deliverable back to what was there before.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
