<?php
/**
 * Title: Contact
 * Slug: tracy/section-contact
 * Categories: tracy
 * Description: Contact section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-contact py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-contact py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-grid tracy-contact__grid max-w-page mx-auto grid gap-12 sm:grid-cols-[1fr_1.2fr]"} -->
<div class="wp-block-group tracy-grid tracy-contact__grid max-w-page mx-auto grid gap-12 sm:grid-cols-[1fr_1.2fr]">
<!-- wp:group {"className":"tracy-contact__copy"} -->
<div class="wp-block-group tracy-contact__copy">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Contact</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":2,"className":"text-2xl mb-3"} -->
<h2 class="wp-block-heading text-2xl mb-3">Tell us about your sites</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead"} -->
<p class="tracy-lead">A few lines is enough. We reply within one working day.</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-meta mb-0"} -->
<p class="tracy-meta mb-0">hello@example.com</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-contact__form"} -->
<div class="wp-block-group tracy-contact__form">
<!-- wp:html -->
<form class="tracy-form tracy-form--contact grid gap-4 p-6 bg-surface border border-border-soft rounded-lg" action="#" method="post">
<label class="tracy-field grid gap-1"><span class="tracy-field__label text-sm text-fg-2">Name</span><input class="tracy-field__input font-[inherit] p-3 border border-border rounded-md bg-bg text-fg" type="text" name="contact_name" autocomplete="name" required></label>
<label class="tracy-field grid gap-1"><span class="tracy-field__label text-sm text-fg-2">Email</span><input class="tracy-field__input font-[inherit] p-3 border border-border rounded-md bg-bg text-fg" type="email" name="contact_email" autocomplete="email" required></label>
<label class="tracy-field grid gap-1"><span class="tracy-field__label text-sm text-fg-2">Subject</span><input class="tracy-field__input font-[inherit] p-3 border border-border rounded-md bg-bg text-fg" type="text" name="contact_subject" required></label>
<label class="tracy-field grid gap-1"><span class="tracy-field__label text-sm text-fg-2">Message</span><textarea class="tracy-field__input font-[inherit] p-3 border border-border rounded-md bg-bg text-fg" name="contact_message" rows="5" required></textarea></label>
<button class="tracy-btn tracy-btn--primary" type="submit">Send</button>
</form>
<!-- /wp:html -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
