<?php
/**
 * Title: Landing page
 * Slug: tracy/landing
 * Categories: tracy
 * Description: The whole landing page, section by section, in the order the design library shows it. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:pattern {"slug":"tracy/section-hero"} /-->
<!-- wp:pattern {"slug":"tracy/section-social-proof"} /-->
<!-- wp:pattern {"slug":"tracy/section-problem"} /-->
<!-- wp:pattern {"slug":"tracy/section-pillars"} /-->
<!-- wp:pattern {"slug":"tracy/section-how-it-works"} /-->
<!-- wp:pattern {"slug":"tracy/section-cta-inline"} /-->
<!-- wp:pattern {"slug":"tracy/section-features"} /-->
<!-- wp:pattern {"slug":"tracy/section-proof"} /-->
<!-- wp:pattern {"slug":"tracy/section-faq"} /-->
<!-- wp:pattern {"slug":"tracy/section-pricing"} /-->
<!-- wp:pattern {"slug":"tracy/section-cta-final"} /-->
