<?php
/**
 * Title: Hero
 * Slug: tracy/section-hero
 * Categories: tracy
 * Description: Hero section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-hero py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-hero py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-hero__inner max-w-page mx-auto grid gap-8 items-center"} -->
<div class="wp-block-group tracy-hero__inner max-w-page mx-auto grid gap-8 items-center">
<!-- wp:group {"className":"tracy-hero__copy"} -->
<div class="wp-block-group tracy-hero__copy">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">AI workstation for websites</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":1,"className":"tracy-display"} -->
<h1 class="wp-block-heading tracy-display">One desk for every site you run</h1>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead"} -->
<p class="tracy-lead">Tracy pairs an AI agent with each of your sites, armed with skills for WordPress, Joomla and Shopify.</p>
<!-- /wp:paragraph -->
<!-- wp:buttons {"className":"tracy-actions"} -->
<div class="wp-block-buttons tracy-actions">
<!-- wp:button {"className":"tracy-btn tracy-btn--primary"} -->
<div class="wp-block-button tracy-btn tracy-btn--primary"><a class="wp-block-button__link wp-element-button" href="#">Download for macOS</a></div>
<!-- /wp:button -->
<!-- wp:button {"className":"is-style-outline tracy-btn tracy-btn--ghost"} -->
<div class="wp-block-button is-style-outline tracy-btn tracy-btn--ghost"><a class="wp-block-button__link wp-element-button" href="#">See pricing</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons -->
<!-- wp:paragraph {"className":"tracy-hero__note tracy-meta mt-4"} -->
<p class="tracy-hero__note tracy-meta mt-4">No credit card · Cancel anytime</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:image {"className":"tracy-hero__media","sizeSlug":"large"} -->
<figure class="wp-block-image size-large tracy-hero__media"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
