<?php
/**
 * Title: Call to action, inline
 * Slug: tracy/section-cta-inline
 * Categories: tracy
 * Description: Call to action, inline section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-cta-inline pb-section-phone sm:pb-section-tablet lg:pb-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-cta-inline pb-section-phone sm:pb-section-tablet lg:pb-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-cta-inline__box max-w-page mx-auto flex flex-wrap items-center justify-between gap-6 p-8 rounded-lg border border-accent/40 bg-accent/10"} -->
<div class="wp-block-group tracy-cta-inline__box max-w-page mx-auto flex flex-wrap items-center justify-between gap-6 p-8 rounded-lg border border-accent/40 bg-accent/10">
<!-- wp:group {"className":"tracy-cta-inline__copy"} -->
<div class="wp-block-group tracy-cta-inline__copy">
<!-- wp:heading {"level":3,"className":"text-xl mb-1"} -->
<h3 class="wp-block-heading text-xl mb-1">See it on your own work in minutes</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-meta mb-0"} -->
<p class="tracy-meta mb-0">No credit card · Cancel anytime</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:buttons {"className":"tracy-actions"} -->
<div class="wp-block-buttons tracy-actions">
<!-- wp:button {"className":"tracy-btn tracy-btn--primary"} -->
<div class="wp-block-button tracy-btn tracy-btn--primary"><a class="wp-block-button__link wp-element-button" href="#">Get started</a></div>
<!-- /wp:button -->
</div>
<!-- /wp:buttons -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
