<?php
/**
 * Title: Team
 * Slug: tracy/section-team
 * Categories: tracy
 * Description: Team section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-team py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-team py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-section__inner max-w-page mx-auto"} -->
<div class="wp-block-group tracy-section__inner max-w-page mx-auto">
<!-- wp:group {"className":"tracy-section__head max-w-[62ch] mb-8"} -->
<div class="wp-block-group tracy-section__head max-w-[62ch] mb-8">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Team</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":2,"className":"text-2xl mb-3"} -->
<h2 class="wp-block-heading text-2xl mb-3">The people who answer when you write in</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead mb-0"} -->
<p class="tracy-lead mb-0">Small enough that you learn our names, long enough that we remember yours.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-grid tracy-team__grid grid gap-6 sm:grid-cols-2 lg:grid-cols-4"} -->
<div class="wp-block-group tracy-grid tracy-team__grid grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
<!-- wp:group {"className":"tracy-card tracy-person p-6 flex flex-col"} -->
<div class="wp-block-group tracy-card tracy-person p-6 flex flex-col">
<!-- wp:image {"className":"tracy-card__media tracy-person__photo mb-4"} -->
<figure class="wp-block-image tracy-card__media tracy-person__photo mb-4"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
<!-- wp:heading {"level":3,"className":"tracy-person__name text-lg m-0 mb-1"} -->
<h3 class="wp-block-heading tracy-person__name text-lg m-0 mb-1">Mai Tran</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-person__role tracy-meta mb-3"} -->
<p class="tracy-person__role tracy-meta mb-3">Founder</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-person__bio mb-0"} -->
<p class="tracy-person__bio mb-0">Reads every support thread before anyone else does.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card tracy-person p-6 flex flex-col"} -->
<div class="wp-block-group tracy-card tracy-person p-6 flex flex-col">
<!-- wp:image {"className":"tracy-card__media tracy-person__photo mb-4"} -->
<figure class="wp-block-image tracy-card__media tracy-person__photo mb-4"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
<!-- wp:heading {"level":3,"className":"tracy-person__name text-lg m-0 mb-1"} -->
<h3 class="wp-block-heading tracy-person__name text-lg m-0 mb-1">Hai Dang</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-person__role tracy-meta mb-3"} -->
<p class="tracy-person__role tracy-meta mb-3">Engineering</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-person__bio mb-0"} -->
<p class="tracy-person__bio mb-0">Keeps the deploy boring, which is the whole job.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card tracy-person p-6 flex flex-col"} -->
<div class="wp-block-group tracy-card tracy-person p-6 flex flex-col">
<!-- wp:image {"className":"tracy-card__media tracy-person__photo mb-4"} -->
<figure class="wp-block-image tracy-card__media tracy-person__photo mb-4"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
<!-- wp:heading {"level":3,"className":"tracy-person__name text-lg m-0 mb-1"} -->
<h3 class="wp-block-heading tracy-person__name text-lg m-0 mb-1">Lena Fischer</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-person__role tracy-meta mb-3"} -->
<p class="tracy-person__role tracy-meta mb-3">Design</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-person__bio mb-0"} -->
<p class="tracy-person__bio mb-0">Draws the thing before anyone argues about the thing.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-card tracy-person p-6 flex flex-col"} -->
<div class="wp-block-group tracy-card tracy-person p-6 flex flex-col">
<!-- wp:image {"className":"tracy-card__media tracy-person__photo mb-4"} -->
<figure class="wp-block-image tracy-card__media tracy-person__photo mb-4"><img src="/wp-content/themes/tracy/assets/img/hero-placeholder.svg" alt=""/></figure>
<!-- /wp:image -->
<!-- wp:heading {"level":3,"className":"tracy-person__name text-lg m-0 mb-1"} -->
<h3 class="wp-block-heading tracy-person__name text-lg m-0 mb-1">Sam Okafor</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-person__role tracy-meta mb-3"} -->
<p class="tracy-person__role tracy-meta mb-3">Support</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-person__bio mb-0"} -->
<p class="tracy-person__bio mb-0">Answers on Sunday, then tells us to fix the cause.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
