<?php
/**
 * Title: How it works
 * Slug: tracy/section-how-it-works
 * Categories: tracy
 * Description: How it works section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-how py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-how py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-section__inner max-w-page mx-auto"} -->
<div class="wp-block-group tracy-section__inner max-w-page mx-auto">
<!-- wp:group {"className":"tracy-section__head max-w-[62ch] mb-8"} -->
<div class="wp-block-group tracy-section__head max-w-[62ch] mb-8">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">How it works</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":2,"className":"text-2xl mb-3"} -->
<h2 class="wp-block-heading text-2xl mb-3">Up and running in three steps</h2>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"tracy-lead mb-0"} -->
<p class="tracy-lead mb-0">No migration project. No six-week rollout.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-grid tracy-steps grid gap-6 sm:grid-cols-2 lg:grid-cols-3"} -->
<div class="wp-block-group tracy-grid tracy-steps grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
<!-- wp:group {"className":"tracy-step"} -->
<div class="wp-block-group tracy-step">
<!-- wp:paragraph {"className":"tracy-step__n inline-grid place-items-center w-12 h-12 rounded-pill bg-accent text-accent-on font-display text-lg font-bold mb-4"} -->
<p class="tracy-step__n inline-grid place-items-center w-12 h-12 rounded-pill bg-accent text-accent-on font-display text-lg font-bold mb-4">1</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"text-lg mb-2"} -->
<h3 class="wp-block-heading text-lg mb-2">Add a site</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"mb-0"} -->
<p class="mb-0">Point Tracy at a site you already run, or start a new one in ninety seconds.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-step"} -->
<div class="wp-block-group tracy-step">
<!-- wp:paragraph {"className":"tracy-step__n inline-grid place-items-center w-12 h-12 rounded-pill bg-accent text-accent-on font-display text-lg font-bold mb-4"} -->
<p class="tracy-step__n inline-grid place-items-center w-12 h-12 rounded-pill bg-accent text-accent-on font-display text-lg font-bold mb-4">2</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"text-lg mb-2"} -->
<h3 class="wp-block-heading text-lg mb-2">Ask for the change</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"mb-0"} -->
<p class="mb-0">Describe it once. The agent drafts it with the skills that fit that platform.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-step"} -->
<div class="wp-block-group tracy-step">
<!-- wp:paragraph {"className":"tracy-step__n inline-grid place-items-center w-12 h-12 rounded-pill bg-accent text-accent-on font-display text-lg font-bold mb-4"} -->
<p class="tracy-step__n inline-grid place-items-center w-12 h-12 rounded-pill bg-accent text-accent-on font-display text-lg font-bold mb-4">3</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":3,"className":"text-lg mb-2"} -->
<h3 class="wp-block-heading text-lg mb-2">Review, then publish</h3>
<!-- /wp:heading -->
<!-- wp:paragraph {"className":"mb-0"} -->
<p class="mb-0">See it before it goes live. Approve, and it lands; change your mind, and it comes back.</p>
<!-- /wp:paragraph -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
