<?php
/**
 * Title: Social proof
 * Slug: tracy/section-social-proof
 * Categories: tracy
 * Description: Social proof section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-social-proof py-8 px-container-phone sm:px-container-tablet lg:px-container-desktop text-center"} -->
<section class="wp-block-group tracy-section tracy-social-proof py-8 px-container-phone sm:px-container-tablet lg:px-container-desktop text-center">
<!-- wp:group {"className":"tracy-section__inner max-w-page mx-auto"} -->
<div class="wp-block-group tracy-section__inner max-w-page mx-auto">
<!-- wp:paragraph {"className":"tracy-social-proof__rating tracy-meta text-fg-2"} -->
<p class="tracy-social-proof__rating tracy-meta text-fg-2">★★★★★ Rated 4.9/5 by 12,000+ teams</p>
<!-- /wp:paragraph -->
<!-- wp:paragraph {"className":"tracy-eyebrow tracy-social-proof__label"} -->
<p class="tracy-eyebrow tracy-social-proof__label">Trusted by teams at</p>
<!-- /wp:paragraph -->
<!-- wp:list {"className":"tracy-logos flex flex-wrap justify-center gap-x-12 gap-y-6 m-0 font-display text-lg font-bold text-muted tracking-display"} -->
<ul class="wp-block-list tracy-logos flex flex-wrap justify-center gap-x-12 gap-y-6 m-0 font-display text-lg font-bold text-muted tracking-display">
<!-- wp:list-item -->
<li>Northwind</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Acme</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Globex</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Initech</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>Umbrella</li>
<!-- /wp:list-item -->
</ul>
<!-- /wp:list -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
