<?php
/**
 * Title: FAQ
 * Slug: tracy/section-faq
 * Categories: tracy
 * Description: FAQ section of the Tracy section library. Generated by packages/cms/tracy-cms-sections/scripts/build.mjs — edit the source there, not this file.
 *
 * @package tracy
 */
?>
<!-- wp:group {"tagName":"section","className":"tracy-section tracy-section--band tracy-faq bg-surface border-y border-border-soft py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop"} -->
<section class="wp-block-group tracy-section tracy-section--band tracy-faq bg-surface border-y border-border-soft py-section-phone sm:py-section-tablet lg:py-section-desktop px-container-phone sm:px-container-tablet lg:px-container-desktop">
<!-- wp:group {"className":"tracy-section__inner max-w-page mx-auto"} -->
<div class="wp-block-group tracy-section__inner max-w-page mx-auto">
<!-- wp:group {"className":"tracy-section__head max-w-[62ch] mb-8"} -->
<div class="wp-block-group tracy-section__head max-w-[62ch] mb-8">
<!-- wp:paragraph {"className":"tracy-eyebrow"} -->
<p class="tracy-eyebrow">Before you ask</p>
<!-- /wp:paragraph -->
<!-- wp:heading {"level":2,"className":"text-2xl mb-0"} -->
<h2 class="wp-block-heading text-2xl mb-0">Your questions, answered</h2>
<!-- /wp:heading -->
</div>
<!-- /wp:group -->
<!-- wp:group {"className":"tracy-faq__list max-w-[62ch] border-b border-border-soft"} -->
<div class="wp-block-group tracy-faq__list max-w-[62ch] border-b border-border-soft">
<!-- wp:details {"className":"tracy-faq__item border-t border-border-soft py-4 m-0"} -->
<details class="wp-block-details tracy-faq__item border-t border-border-soft py-4 m-0"><summary>Does the agent touch my live site directly?</summary><!-- wp:paragraph {"className":"mt-3 mb-0 text-fg-2"} -->
<p class="mt-3 mb-0 text-fg-2">No. Work is drafted and reviewed first; only an approved change reaches the running site.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"className":"tracy-faq__item border-t border-border-soft py-4 m-0"} -->
<details class="wp-block-details tracy-faq__item border-t border-border-soft py-4 m-0"><summary>Which platforms are supported?</summary><!-- wp:paragraph {"className":"mt-3 mb-0 text-fg-2"} -->
<p class="mt-3 mb-0 text-fg-2">WordPress and Joomla today, Shopify next. Each has its own set of skills.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"className":"tracy-faq__item border-t border-border-soft py-4 m-0"} -->
<details class="wp-block-details tracy-faq__item border-t border-border-soft py-4 m-0"><summary>What happens if a change goes wrong?</summary><!-- wp:paragraph {"className":"mt-3 mb-0 text-fg-2"} -->
<p class="mt-3 mb-0 text-fg-2">Every change is recorded under its own id. One call puts the whole deliverable back.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
<!-- wp:details {"className":"tracy-faq__item border-t border-border-soft py-4 m-0"} -->
<details class="wp-block-details tracy-faq__item border-t border-border-soft py-4 m-0"><summary>Can I cancel?</summary><!-- wp:paragraph {"className":"mt-3 mb-0 text-fg-2"} -->
<p class="mt-3 mb-0 text-fg-2">Any time. Clearing the token revokes everything at once.</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->
</div>
<!-- /wp:group -->
</div>
<!-- /wp:group -->
</section>
<!-- /wp:group -->
